### ISSUE TITLE
Error ansible 2.0

### ISSUE THREAD

**Issue by resyst-it** [jonathanio/ansible-roles-strongswan#1]
Hello,

I have an error when i use your playbook in the readme. I have this error :

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/etc/ansible/playbook/test.yml': line 5, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


---
^ here
```

Do you have an idea ?

Thank you.

**Comment by jonathanio** [comment]
This seems to be an error within the Playbook itself, rather than the role. Can you post the playbook `test.yml` so I can take a look?

**Comment by resyst-it** [comment]
I just want to test your playbook so i just copy you playbook exemple.
I git clone you repository that's why the role is ansible-role-strongswan
```
- hosts: ipsec_server
  roles:
     - { role: ansible-role-strongswan, tags: ['ipsec'] }

---
strongswan_hosts:
  - name: example
    conn:
      auto: route
      type: tunnel
      authby: psk
      keyexchange: ikev2
      lifetime: 3h
      ike: aes256gcm16-modp2048!
      esp: aes256gcm16-modp2048!
      ikelifetime: 24h
    left:
      address: 12.34.56.78
      protoport: 47
    right:
      address: 87.65.43.21
      protoport: 47
    secret: something_needs_to_go_here
```

I don't know where is my mistake.
